### PR TITLE
Fix typo and suggestion

### PR DESCRIPTION
**Pull request by aJchemist**
First, thank for the garden hard work :+1: 

I suggest new `defnstyle` and `defnstylesheet` macros for live coding. `def` feels like static declaration.

```clojure
(def ^:dynamic color-palette
  {:background "#000000"
   :foreground "#ececec"})

(defnstyles base
  ((rule :html :body)
   {:margin "0" :padding "0"
    :height "100%"
    :font [["400" "16px/18px"] 'Roboto 'sans-serif]
    :color (color-palette :foreground)
    :background-color (color-palette :background)})

(defnstylesheet root-css
  (base))

(root-css {:pretty-print? false})

(binding [color-palette (assoc color-palette :background (rgb 20 20 20))]
    (root-css {:pretty-print? false}))
```

### CODE REVIEW

**Comment by noprompt** [comment]
Let me think about this. I'd actually prefer `defstylesheetfn` and the like because the `-fn` part is typically seen at the end (e.g. `letfn`, `some-fn`, etc.). Other committers might have a different opinion. Since I haven't been working on Garden much lately I'll let them chime in with thoughts.

**Comment by aJchemist** [comment]
Alright. when naming chosen, please ping me! 

Beforehand I've modified.

**Comment by aJchemist** [comment]
Add missing binding arguments

```clojure
(defnstylesfn base [& [color]]
  ((rule :html :body)
   {:margin "0" :padding "0"
    :height "100%"
    :font [["400" "16px/18px"] 'Roboto 'sans-serif]
    :color (or color (color-palette :foreground))
    :background-color (color-palette :background)}))

(defnstylesheetfn root-css []
  (base))
```

**Comment by noprompt** [comment]
@aJchemist Hey. Just to let you know I haven't forgotten about this, I've simply been busy with other things and haven't had time to think it over. @priyatam, @jeluard: do either of you have any thoughts on this?

**Comment by jeluard** [comment]
No particular opinion about this. I would not use it but that's probably something people would expect.

**Comment by priyatam** [comment]
@aJchemist thanks for the PR. While this seems like a nice idea for live-coding, it's opinionated and the names are confusing to those who are used to garden/css. You can use atoms instead, store props and swap the values from the console in Chrome.

**Pull request closed without merging**
